name = "willies-keys"
compatibility_date = "2024-11-05"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

pages_build_output_dir = "svelte-kit/cloudflare"

[[d1_databases]]
binding = "willies_keys_db"
database_name = "willies-keys-db"
database_id = "249ec1d9-ac4e-4cb9-aaf9-c5b2b07e4ae2"
